type Query {
    me: String
    logout: String
}

type Mutation {
    login(user: UserInput!): LoginResponse
}

enum LoginResponse {
    WrongPassword
    Overloading
    Ok
    WebSocketFailed
    HeavyLogin
    WhereAmI
}

input UserInput {
    username: String!
    password: String!
}

type User {
    username: String!
    password: String
}
