export const container: string
export const mainWindow: string
export const cursor: string
export const bbsInput: string
export const menu: string
export const navigation: string
export const menuSpace: string
export const wrapper: string
export const keepSpace: string
export const mainContainer: string
export const bbsWrapper: string
